# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  libsql:
    image: ghcr.io/tursodatabase/libsql-server:latest
    container_name: mts_libsql
    hostname: libsql
    ports:
      - 5001:5001
      - 8080:8080
    volumes:
      - libsql_data:/var/lib/sqld/data
      - libsql_exts:/var/lib/sqld/extensions
    environment:
        SQLD_NODE: 'primary'
        SQLD_DB_PATH: '/var/lib/sqld/data/data.sqld'
        SQLD_GRPC_LISTEN_ADDR: '0.0.0.0:5001'
        SQLD_HTTP_LISTEN_ADDR: '0.0.0.0:8080'
    # @ref: https://github.com/tursodatabase/libsql/tree/main/libsql-server#sqlite-extensions-support
    # command: 'sqld --no-welcome --extensions-path=/var/lib/sqld/extensions'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  mailpit:
    image: axllent/mailpit:latest
    container_name: mts_mailpit
    restart: unless-stopped
    volumes:
      - mailpit_data:/data
    ports:
      - '1025:1025' # port the SMTP server should be accessible on
      - '8025:8025' # port the web interface should be accessible on
    environment:
      # https://github.com/axllent/mailpit/wiki/Runtime-options
      TZ: 'Asia/Jakarta'

volumes:
  libsql_data:
    driver: local
  libsql_exts:
    driver: local
  mailpit_data:
    driver: local
