# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  libsql:
    image: ghcr.io/tursodatabase/libsql-server:latest
    container_name: kyval_libsql
    hostname: libsql
    ports:
      - 5001:5001
      - 8080:8080
    volumes:
      - libsql_data:/var/lib/sqld/data
      - libsql_exts:/var/lib/sqld/extensions
    environment:
        SQLD_NODE: 'primary'
        SQLD_DB_PATH: '/var/lib/sqld/data/data.sqld'
        SQLD_GRPC_LISTEN_ADDR: '0.0.0.0:5001'
        SQLD_HTTP_LISTEN_ADDR: '0.0.0.0:8080'
    # @ref: https://github.com/tursodatabase/libsql/tree/main/libsql-server#sqlite-extensions-support
    # command: 'sqld --no-welcome --extensions-path=/var/lib/sqld/extensions'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  libsql_data:
    driver: local
  libsql_exts:
    driver: local
